### ISSUE TITLE
总是加载失败

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#105]
看不到任何帖子
## System Info
- App Version: 33
- OS Version: 2.6.35.7 (ZCKI1)
- OS API Level: 10
- Device: GT-I9100G
- Model: GT-I9100G (GT-I9100G)
- Reporter: [雁过留痕](http://www.cc98.org/dispuser.asp?name=%E9%9B%81%E8%BF%87%E7%95%99%E7%97%95)

**Comment by djj0809** [comment]
请升级最新版
