### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#107]
建议增加一个夜间模式→_→
## System Info
- App Version: 42
- OS Version: 3.4.0-g3720aca-00058-g5720272 (eng.nubia.20131212.184503)
- OS API Level: 17
- Device: NX403A
- Model: NX403A (NX403A)
- Reporter: [冬石之浙](http://www.cc98.org/dispuser.asp?name=%E5%86%AC%E7%9F%B3%E4%B9%8B%E6%B5%99)

**Comment by djj0809** [comment]
没人力做...
