### ISSUE TITLE
电脑数码打不开

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#108]
版面打不开，帖子能开
## System Info
- App Version: 42
- OS Version: 3.4.5-1928161 (I9500ZCUFML1)
- OS API Level: 18
- Device: ja3g
- Model: GT-I9500 (ja3gzc)
- Reporter: [klgkaka](http://www.cc98.org/dispuser.asp?name=klgkaka)

**Comment by djj0809** [comment]
现在貌似可以了...
