### ISSUE TITLE
制定板块

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#119]
客户端是不是无法制定板块？
## System Info
- App Version: 42
- OS Version: 3.0.39-user-svn2615 (M03X.Flyme_1.1.8.1361431298)
- OS API Level: 15
- Device: mx
- Model: M030 (meizu_mx)
- Reporter: [简约](http://www.cc98.org/dispuser.asp?name=%E7%AE%80%E7%BA%A6)

**Comment by djj0809** [comment]
是的
