### ISSUE TITLE
建议增加夜间模式

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#129]
晚上在被窝里太亮了
## System Info
- App Version: 42
- OS Version: 3.4.0-g52db9c3-01077-gb91661e (JLB33.0)
- OS API Level: 16
- Device: aries
- Model: MI 2S (aries)
- Reporter: [因为懂得](http://www.cc98.org/dispuser.asp?name=%E5%9B%A0%E4%B8%BA%E6%87%82%E5%BE%97)

**Comment by djj0809** [comment]
该把屏幕调暗点...
