### ISSUE TITLE
缓存bug

### ISSUE THREAD

**Issue by djj0809** [ZJU-CC98/MyCC98#17]
通过最近回复点进去有bug

**Comment by zsy056** [comment]
上一次提交中已经修复
在 2013-6-19 下午4:31，"DJ" notifications@github.com写道：

**Comment by djj0809** [comment]
还是老样子啊...

**Comment by djj0809** [comment]
@zsy056

**Comment by djj0809** [comment]
当帖子列表第一次由于网络原因失败后的内容也被缓存了，而且列表页加载失败的时候目前还不能刷新。
还有一个问题是每页帖子里会包含帖子总页数，这个信息其实会比较快更新，缓存起来有一定问题

**Comment by djj0809** [comment]
@zsy056
