### ISSUE TITLE
追踪去哪儿了？

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#189]
找来找去没找到追踪，网站上也有的功能，是没开发嘛？有些长帖没法看
## System Info
- App Version: 45
- OS Version: 3.4.0-g52db9c3-01077-gb91661e (JLB34.0)
- OS API Level: 16
- Device: aries
- Model: MI 2SC (aries)
- Reporter: [邪](http://www.cc98.org/dispuser.asp?name=%E9%82%AA)

**Comment by djj0809** [comment]
目前不支持
