### ISSUE TITLE
不能删自己的贴

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#67]
## System Info
- App Version: 34
- OS Version: 3.0.8-00785-g7d790a4 (C01B115SP02)
- OS API Level: 17
- Device: hwp6-t00
- Model: HUAWEI P6-T00 (P6-T00)
- Reporter: [徐涛](http://www.cc98.org/dispuser.asp?name=%E5%BE%90%E6%B6%9B)

**Comment by djj0809** [comment]
没有此功能
