### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#70]
点开图的时候想要双指缩放一下结果直接秒退，试验多次都是这样，能否改进一下，哪怕不能缩放也不要秒退啊，手贱的时候就会去拉。。THX
PS:我的爪机是HTC 920E，系统是4.2.2
## System Info
- App Version: 34
- OS Version: 3.4.10-g013e2fc (222759.1)
- OS API Level: 17
- Device: dlxu
- Model: HTC X920e (dlxu)
- Reporter: [hezyyn](http://www.cc98.org/dispuser.asp?name=hezyyn)

**Comment by djj0809** [comment]
Fixed
