### ISSUE TITLE
回复帖子

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#71]
打开回复框之后默认输入主题了啊QAQ求改回默认输入内容
## System Info
- App Version: 34
- OS Version: 3.4.10-g4e8a4af (157254.101)
- OS API Level: 16
- Device: villec2
- Model: HTC One S (villec2)
- Reporter: [子霏非鱼](http://www.cc98.org/dispuser.asp?name=%E5%AD%90%E9%9C%8F%E9%9D%9E%E9%B1%BC)

**Comment by djj0809** [comment]
已解决
