### ISSUE TITLE
查看新帖会闪退

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#73]
在查看新帖的时候下滚，滚几次就刷不出来并且闪退了
## System Info
- App Version: 35
- OS Version: 3.4.10-g013e2fc (222759.1)
- OS API Level: 17
- Device: dlxu
- Model: HTC X920e (dlxu)
- Reporter: [hezyyn](http://www.cc98.org/dispuser.asp?name=hezyyn)

**Comment by djj0809** [comment]
已解决
