### ISSUE TITLE
建议加入帖子编辑功能

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#75]
自己的帖子我无法修改，捉急啊！还有个人信息也不能修改，捉急啊！
## System Info
- App Version: 35
- OS Version: 3.0.8-gc58e832 (C92B128)
- OS API Level: 16
- Device: hwa199
- Model: HUAWEI A199 (A199)
- Reporter: [墨澜](http://www.cc98.org/dispuser.asp?name=%E5%A2%A8%E6%BE%9C)

**Comment by djj0809** [comment]
请上浏览器修改，谢谢合作
