### ISSUE TITLE
一个很蛋疼的bug

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#76]
后台运行时，从桌面图标打开应用时自动出现首页，而不是原先的页面，只有长按home键打开应用才会出现原先页面。
## System Info
- App Version: 35
- OS Version: 3.4.0-g52db9c3-01061-g6e5b457 (3.9.27)
- OS API Level: 16
- Device: aries
- Model: MI 2S (aries)
- Reporter: [airlekya](http://www.cc98.org/dispuser.asp?name=airlekya)

**Comment by djj0809** [comment]
个人使用没有发现过这个问题
