### ISSUE TITLE
收藏夹功能

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#77]
貌似没有收藏夹功能希望可以改进哈
## System Info
- App Version: 35
- OS Version: 2.6.35.7-I9100ZSKI3-CL603802 (ZSKI3)
- OS API Level: 10
- Device: GT-I9100
- Model: GT-I9100 (GT-I9100)
- Reporter: [爱夏](http://www.cc98.org/dispuser.asp?name=%E7%88%B1%E5%A4%8F)

**Comment by djj0809** [comment]
抱歉手机端一般不提供不常用的功能
