### ISSUE TITLE
没法追踪帖子，没法编辑自己的帖子

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#78]
如题
## System Info
- App Version: 35
- OS Version: 3.4.0-g52db9c3-01063-gfa5a455 (3.10.11)
- OS API Level: 16
- Device: aries
- Model: MI 2S (aries)
- Reporter: [airlekya](http://www.cc98.org/dispuser.asp?name=airlekya)

**Comment by djj0809** [comment]
抱歉这两个功能在可见的范围内也没有计划开发
