### ISSUE TITLE
夜间模式

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#81]
建议加入夜间模式
## System Info
- App Version: 38
- OS Version: 3.0.31-1174148 (N7100ZSDME1)
- OS API Level: 16
- Device: t03g
- Model: GT-N7100 (t03gzs)
- Reporter: [hlalh](http://www.cc98.org/dispuser.asp?name=hlalh)

**Comment by djj0809** [comment]
不会有的。没有精力做，抱歉
