### ISSUE TITLE
看不到帖子内容了

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#90]
小米1s，已更新到最新版
## System Info
- App Version: 39
- OS Version: 3.4.0-perf-g1ccebb5-00146-gd6845ec (3.11.22)
- OS API Level: 16
- Device: mione_plus
- Model: MI 1S (mione_plus)
- Reporter: [镁粉儿](http://www.cc98.org/dispuser.asp?name=%E9%95%81%E7%B2%89%E5%84%BF)

**Comment by owensss** [comment]
哈哈哈这个想法真好，学长的回复也会自动转发到 用户 那边？
