### ISSUE TITLE
一个关于客户端的建议

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#94]
你好！我很喜欢你们做的客户端软件，它让我浏览98的过程中节省了不少功夫。不过我很希望能够有消息推送的功能，希望能够给你们带来一点参考建议，谢谢！
## System Info
- App Version: 40
- OS Version: 3.4.0+1.0.21100-313065-g1ccebb5-00193-gcbc50fc (n7v_zg)
- OS API Level: 16
- Device: LT26i
- Model: LT26i (LT26i_1257-7763)
- Reporter: [稳压二极管](http://www.cc98.org/dispuser.asp?name=%E7%A8%B3%E5%8E%8B%E4%BA%8C%E6%9E%81%E7%AE%A1)

**Comment by djj0809** [comment]
目前来看不现实...
