### ISSUE TITLE
性别图标显示问题

### ISSUE THREAD

**Issue by MyCC98User** [ZJU-CC98/MyCC98#96]
怎么大多数都显示女生图标呀
## System Info
- App Version: 40
- OS Version: 3.4.10-g013e2fc (222759.1)
- OS API Level: 17
- Device: dlxu
- Model: HTC X920e (dlxu)
- Reporter: [hezyyn](http://www.cc98.org/dispuser.asp?name=hezyyn)

**Comment by djj0809** [comment]
我也不知道...
